catalog_name: sandbox
schema_name: sb_adan

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - Temperature
  - Humidity
  - Wind_Speed

target: Zone_1_Power_Consumption

id_col: DateTime

mlflow_experiment_name: /Shared/mlops_course_nico